service: default
runtime: go111
instance_class: F1
automatic_scaling:
  max_idle_instances: 0
  min_idle_instances: 0
  max_concurrent_requests: 80
handlers:
- url: /.*
  script: _go_app
env_variables:
  TENOR_KEY: ""
